### ISSUE TITLE
License

### ISSUE THREAD

**Issue by PoisonNinja** [exscape/exscapeOS#3]
I forked this project and modified a bunch of things. I was wondering, what license is all this code under? Since I can't find a license, this means that I technically can't really do anything with the code.

**Comment by exscape** [comment]
Hey! I noticed, but I assumed you were one of the guys who asked me via e-mail recently. :-)
Anyway, I've been meaning to assign a license, but haven't gotten to it. Most likely, that will end up being the MIT license. You hereby have my permission to treat the code as if it's under the MIT license (the parts that I've written, at least, i.e. excluding NewLib etc.).

**Comment by PoisonNinja** [comment]
Thanks! I'll add a LICENSE file and headers to each file.

**Comment by PoisonNinja** [comment]
One more question: Is there a name that you would want the license to be attributed to? If not, I'll just put it as exscape.

**Comment by exscape** [comment]
Thomas Backman <serenity@exscape.org> would be preferable. :)

**Comment by PoisonNinja** [comment]
Great, thanks!

**Comment by PoisonNinja** [comment]
Resolved by PoisonNinja/finix@8817edca94b74f41b3fc5e1a55dd4971a486a848
